### ISSUE TITLE
Blazor / .NET 6.0 readiness?

### ISSUE THREAD

**Issue by damageboy** [excubo-ag/Blazor.Canvas#155]
The current master + demo seems to fail for me.

When compiling locally with the official release of .net core 6.0
I'm getting crashes with chrome (`Version 95.0.4638.69 (Official Build) (64-bit)
`):
![image](https://user-images.githubusercontent.com/125730/141752270-5662726d-3d7e-4a80-b2c1-80a4436e34b3.png)

With this in the developer console:
![image](https://user-images.githubusercontent.com/125730/141752202-1f91c665-327a-4c65-bf9c-c2d4e163d788.png)

Am I doing something wrong here?

**Comment by stefanloerwald** [comment]
Hi @damageboy,

Looks like I messed up the last update(s). Thanks for notifying me. I'll get to it in a few days. Until then, please revert back to older versions. If you use the source code to use this library, please try to remove the PrivateAssets="all" flag from the package reference of excubo.generators.blazor and see if that resolves it.

Thanks
Stefan

**Comment by wizardars** [comment]
Hi @stefanloerwald, strange, but my experience is different. 
Version 3.0.0 work, but failing with AOT, 3.0.2 version work everywhere, I migrated to .NET 6 with AOT. I don't know what I did specifically. Here are my steps: 
Since I found that installed web tools (AOT) interfere with normal compilation, I split the process into two virtual machines. One for development with VS, another for compilation, VS + AOT for AOT'ing. But now I delete these directories ". vs., bin, obj" before compilation. My results:

| Framework | FPS | Size |
| --- | --- | --- |
| .NET 5 | 2.7| 10 MB |
| .NET 6 | 3.9 | 9 MB |
| .NET 6 AOT | 40.4 | 49 MB|

**Comment by stefanloerwald** [comment]
Hi @damageboy & @wizardars,

I've done some changes to the dependencies. Could you both please check whether everything works now as you expect it to?

Thanks
Stefan

**Comment by wizardars** [comment]
Sure @stefanloerwald ,

ver:3.0.3, Compile chain:MONO, target platform:linux-64
Compiling: +
Test: +

ver:3.0.3, Compile chain:WEB AOT, target platform:linux-64
Compiling: - (*)
Test: -

(*)
Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
AOT'ing 70 assemblies
[ApiGroupGenerator.dll] Exec (with response file contents expanded) in C:\CODE\TT\Web\Client\obj\Release\net6.0\linked: MONO_PATH=C:\CODE\TT\Web\Client\obj\Release\net6.0\linked;C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\;C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\\lib\net6.0 MONO_ENV_OPTIONS= C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.browser-wasm\6.0.0\Sdk\..\tools\mono-aot-cross.exe --debug --llvm "--aot=no-opt,static,direct-icalls,deterministic,dwarfdebug,llvm-path=C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\bin\,static,llvmonly,interp,asmonly,llvm-outfile=C:\CODE\TT\Web\Client\obj\Release\net6.0\wasm\for-publish\ApiGroupGenerator.dll.bc.tmp" "ApiGroupGenerator.dll"

Failed to load method 0x6000011 from 'C:\CODE\TT\Web\Client\obj\Release\net6.0\linked\ApiGroupGenerator.dll' due to Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies..
Mono Ahead of Time compiler - compiling assembly C:\CODE\TT\Web\Client\obj\Release\net6.0\linked\ApiGroupGenerator.dll
Run with MONO_LOG_LEVEL=debug for more information.
AOT of image ApiGroupGenerator.dll failed.

**Comment by stefanloerwald** [comment]
Thanks @wizardars! This will require further investigation on my part... I'll let you know if I find something out, but unfortunately I will not be able to spend time on this soon.

**Comment by wizardars** [comment]
No problem @stefanloerwald , I'll use 3.0.2.

**Comment by stefanloerwald** [comment]
@wizardars There's a chance that v3.0.4 fixes your issue. Cheers, Stefan

**Comment by wizardars** [comment]
The new default project on .NET 6 works with v3.0.4, but my migrated project does not. Apparently, I incorrectly migrated to .NET 6. I'll have to figure it out later. So you can close the Issue. Thanks @stefanloerwald .

**Comment by stefanloerwald** [comment]
@damageboy Is everything fine for you now? If so, we can close this issue. Thanks, Stefan
